# Generated by Django 4.1.7 on 2023-11-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parkingname', models.CharField(max_length=122)),
                ('location', models.CharField(max_length=122)),
                ('phoneno', models.CharField(max_length=122)),
                ('space', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('userno', models.CharField(max_length=12)),
                ('vehicalno', models.CharField(max_length=30)),
                ('vehicaltype', models.CharField(max_length=10)),
            ],
        ),
    ]
