# Generated by Django 4.1.7 on 2023-11-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0003_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
